name: Fly Beta Deploy
on:
  push:
    branches:
      - feat/cicd
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl secrets set VERSION=$(git rev-parse --short "$GITHUB_SHA") --config config/fly-beta.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_BETA }}
      - run: flyctl deploy --remote-only --config config/fly-beta.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_BETA }}
