name: Fly Production Deploy
on:
  release:
    types:
      - published
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl secrets set VERSION=${{ github.event.release.tag_name }} --config config/fly-prod.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_PROD }}
      - run: flyctl deploy --remote-only --config config/fly-prod.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_PROD }}
