name: Docker build

on:
  pull_request:
    # branches:
    #   - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build  .
